URL_SERVICE = "https://cnt-1f8279e3-fbd8-4fb8-a37d-221642c0bafb.containerhub.tripleten-services.com"
DOC_PATH = "/docs/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_USER_PATH = "/api/v1/users/"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"
CREATE_KITS_PATH = "/api/v1/kits/"
